const seedOils = [
  'Soybean Oil',
  'Partially Hydrogenated Soybean Oil',
  'Hydrogenated Soybean Oil',
  'Corn Oil',
  'Partially Hydrogenated Corn Oil',
  'Hydrogenated Corn Oil',
  'Maize Oil',
  'Canola Oil',
  'Rapeseed Oil',
  'Partially Hydrogenated Canola Oil',
  'Hydrogenated Canola Oil',
  'Low Erucic Acid Rapeseed Oil',
  'Cottonseed Oil',
  'Partially Hydrogenated Cottonseed Oil',
  'Hydrogenated Cottonseed Oil',
  'Sunflower Oil',
  'Partially Hydrogenated Sunflower Oil',
  'Hydrogenated Sunflower Oil',
  'Grapeseed Oil',
  'Grape Oil',
  'Palm Oil',
  'Palm Kernel Oil',
  'Partially Hydrogenated Palm Oil',
  'Hydrogenated Palm Oil',
  'Safflower Oil',
  'Partially Hydrogenated Safflower Oil',
  'Hydrogenated Safflower Oil',
  'Hazelnut Oil',
  'Peanut Oil',
  'Partially Hydrogenated Peanut Oil',
  'Hydrogenated Peanut Oil',
  'Partially Hydrogenated Almond Oil',
  'Hydrogenated Almond Oil',
];

export default seedOils;
